### ISSUE TITLE
[Sandbox] KubeService Stack

### ISSUE THREAD

**Issue by dongjiang1989** [cncf/sandbox#15]
### Application contact emails

kubeservicestack@163.com, dongjiang1989@126.com, zhouzhengling@163.com, imlense@163.com

### Project Summary

KubeService Stack = Kubernetes + Custom Service. Build a Kubernetes/KubeEdge enterprise-level peripheral ecosystem

### Project Description

KubeserviceStack provides a complete set of DevOps solutions, covering a full range of observability capabilities such as service registration center, configuration center, business monitoring, traffic monitoring, platform monitoring, event center, and operation records, helping users quickly build observability capabilities. Build CNI plug-ins, CSI plug-ins, CRI plug-ins and Kubernetes Webhook/Controller to achieve non-invasive extensions to Kubernetes.

### Org repo URL

https://github.com/kubeservice-stack

### Project repo URL

N/A

### Additional repos

https://github.com/kubeservice-stack/basa
https://github.com/kubeservice-stack/namespace-node-affinity
https://github.com/kubeservice-stack/custom-limit-range
https://github.com/kubeservice-stack/crane-scheduler
https://github.com/kubeservice-stack/local-cloud-csi-driver
https://github.com/kubeservice-stack/base-image-library
https://github.com/kubeservice-stack/pingmesh-agent
https://github.com/kubeservice-stack/common

### Website URL

https://stack.kubeservice.cn/

### Roadmap

https://github.com/orgs/kubeservice-stack/projects/2

### Roadmap context

future milestore:  
[https://stack.kubeservice.cn/project/](https://stack.kubeservice.cn/project/)

### Contributing Guide

https://github.com/kubeservice-stack/Community/blob/main/CODE_OF_CONDUCT.md

### Code of Conduct (CoC)

https://github.com/kubeservice-stack/Community/blob/main/CODE_OF_CONDUCT.md

### Adopters

N/A

### Contributing or Sponsoring Org

N/A

### Maintainers file

https://github.com/kubeservice-stack/Community/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We believe that KubeServiceStack is in a stable state already and that it can be safely used in production environments.

What is missing right now, is visibility and adoption of the project. We would like to signal that this project is going to stay and that it is able to mature to a point where it becomes completely independent from the original developers (especially me/@dongjiang1989, as I'm contributing 99% of the code at the moment).

To accomplish this, we also need guidance and support from more experienced Open Source communities, especially in the cloud native space.

### Benefit to the Landscape

KubeServiceStack is focused on the infrastructure of cloud native ecosystem, which is vital to the development of cloud native technology. The joining of KubeServiceStack will help CNCF accelerate the evolution of cloud native ecosystem system  in turn benefiting the entire cloud native ecosystem.

### Similar projects

[TKEStack](https://github.com/tkestack/tke)

### Product or Service to Project separation

N/A

**Comment by dongjiang1989** [comment]
The application for KubeServiceStack is ready for review, PTAL when you have time🙏

**Comment by amye** [comment]
TOC will be reviewing these in 2023!

**Comment by dims** [comment]
cc @resouer

**Comment by mariida** [comment]
It appears that the author of this repository has not adhered to the Code of Conduct, which poses a moral hazard.

Evidence of this includes the fact that Nokia's repo CPU-Pooler, which is licensed under BSD, has had its intellectual property stolen and modified to conform to the Apache protocol. 

[nokia/CPU-Pooler](https://github.com/nokia/CPU-Pooler/blob/master/pkg/checkpoint/checkpoint.go)


![image](https://user-images.githubusercontent.com/29575689/219260208-46b00ee2-5a92-4fcc-92b0-7cccb569b5bf.png)



[kubeservice-stack/cpusets-controller](https://github.com/mariida/cpusets-controller/blob/main/pkg/checkpoint/checkpoint.go)
![image](https://user-images.githubusercontent.com/29575689/219260355-2aaea596-da85-47b3-b5dc-c27c522f9d37.png)




For instance, the author forked the crane-scheduler project, which already belongs to the finops foundation, and made changes under the forked name. 

Additionally, the author used a significant amount of code from the `kubernetes-sigs/alibaba-cloud-csi-driver` for their `local-cloud-csi-driver` project, which, while not violating the Apache protocol, may still be inappropriate and may not show respect for the open-source community.



[[alibaba-cloud-csi-driver/orphaned.go at 178a329e9659b1bb72b1cbafacb4c4ce0bb36e80 · kubernetes-sigs/alibaba-cloud-csi-driver (github.com)](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/178a329e9659b1bb72b1cbafacb4c4ce0bb36e80/pkg/om/orphaned.go)](https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/178a329e9659b1bb72b1cbafacb4c4ce0bb36e80/pkg/om/orphaned.go)



[[local-cloud-csi-driver/orphaned.go at master · mariida/local-cloud-csi-driver (github.com)](https://github.com/mariida/local-cloud-csi-driver/blob/master/pkg/om/orphaned.go)](https://github.com/mariida/local-cloud-csi-driver/blob/master/pkg/om/orphaned.go)



Similar situations appear to exist in other repositories, and the author's actions are in serious violation of the fundamental principles of CNCF and go against the spirit of open source.

**Comment by amye** [comment]
This would fall more under the [IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy). 
If accepted by the Technical Oversight Committee, we work through issues through onboarding.

**Comment by mariida** [comment]
These issues cannot be dismissed as solely an IP strategy problem. The author has exploited the lax access rules of the CNCF organization sandbox, compromising the principles of open source and creating a significant moral risk.

The projects the author has presented are mostly duplicates. With only minor modifications to the README and code structure, there is little value to this haphazard patchwork. Instead of providing any tangible benefits, the author's actions have only served to waste everyone's time and fulfill their own **KPI** and other objectives.



IMO, I don't believe it would be worthwhile for others to review this.

**Comment by mariida** [comment]
These issues cannot be dismissed as solely an IP strategy problem. The author has exploited the lax access rules of the CNCF organization sandbox, compromising the principles of open source and creating a significant moral risk.

The projects the author has presented are mostly duplicates. With only minor modifications to the README and code structure, there is little value to this haphazard patchwork. Instead of providing any tangible benefits, the author's actions have only served to waste everyone's time and fulfill his  objectives.

IMO, I don't believe it would be worthwhile for others to review this.

**Comment by dims** [comment]
@mariida thank you for your input. We will take that into consideration.

**Comment by mariida** [comment]
The lenient policy of the sandbox is beneficial for the development of cloud-native solutions. However, prior to TOC review, the code agreement should be scrutinized to weed out instances of code plagiarism and other practices that violate intellectual property rights. In particular, stealing other people's intellectual property rights is a serious mistake. 

It may be necessary to remind colleagues at Nokia that their code may have been compromised，someone steals your code and erases the BSD agreement, it is important to take action. @CsatariGergely https://github.com/mariida/cpusets-controller/blob/main/pkg/checkpoint/checkpoint.go


It is suggested that after submitting the sandbox application,  TOC contributor（now gone） would be allocated to reviewing the code in order to prevent any infringement on the open-source spirit of CNCF.

**Comment by dims** [comment]
@mariida again thanks for your input.

**Comment by CsatariGergely** [comment]
Thanks @mariida for recognising this. I've opened an issue asking for resolution (https://github.com/kubeservice-stack/cpusets-controller/issues/1)

**Comment by cathyhongzhang** [comment]
Looks like this project covers a wide range of functionalities. Could you clarify the overlap and/or differentiation of this project with other projects that provide similar functionalities?
