### ISSUE TITLE
[Sandbox] Ratify

### ISSUE THREAD

**Issue by FeynmanZhou** [cncf/sandbox#96]
### Application contact emails

feynmanzhou@microsoft.com, yizha1@microsoft.com, luisdlp@microsoft.com, sajaya@microsoft.com

### Project Summary

A verification engine on Kubernetes which enables verification of artifact security metadata and admits for deployment only those that comply with policies you create.

### Project Description

Ratify is a workflow engine that coordinates the verification of different supply chain objects for an image as per a given policy. It is a verification framework that can use and coordinate any number of custom verifiers for things like signatures, SBoMs, vulnerability scan results, attestations, and so on. Ratify aggregates the results of these independent verifiers using a policy. This aggregated result can be used to make decisions in the admission controllers.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/deislabs (We are transferring Ratify to a new org https://github.com/ratify-project)

### Project repo URL in scope of application

https://github.com/deislabs/ratify

### Additional repos in scope of the application

https://github.com/deislabs/ratify-web

### Website URL

https://ratify.dev/

### Roadmap

https://github.com/deislabs/ratify/blob/staging/ROADMAP.md

### Contributing Guide

https://github.com/deislabs/ratify/blob/staging/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/deislabs/ratify/blob/staging/CODE_OF_CONDUCT.md

### Adopters

https://github.com/deislabs/ratify/blob/staging/ADOPTERS.md

### Contributing or Sponsoring Org

Microsoft

### Maintainers file

https://github.com/deislabs/ratify/blob/staging/MAINTAINERS

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Ratify is an open and extensible verification framework for container images and other artifacts that can examine and use custom policies that users create to approve deployments in Kubernetes. We believe CNCF is a neutral home for Ratify because it has a flourish and active community can help the future success of Ratify through the development of third-party integrations.

### Benefit to the Landscape

Ratify's mission is to safeguard the container supply chain by ratifying trustworthy and compliant container images and other software artifacts. As a open framework in CNCF security & compliance area, Ratify is designed with different interface models to allow for its integration at different stages of the containers secure supply chain. Ratify has already collaborated and integrated with some CNCF projects and provide joint solutions to CNCF ecosystem users.

### Cloud Native 'Fit'

Ratify enables users to verify artifact security metadata (signatures and attestations including vulnerability reports, SBOM, provenance data, and VEX documents) prior to deployment in Kubernetes clusters and admit for deployment only those that comply with an admission policy that users create. 

With Ratify, cloud-native workloads can be verifiable on deployment, eventually increase the security posture of cloud-native ecosystem users.

### Cloud Native 'Integration'

Notary Project, OPA Gatekeeper, Trivy (non-CNCF), ORAS, Sigstore Cosign (OpenSSF)

### Cloud Native Overlap

To our knowledge, there isn't any direct overlap with other CNCF projects today.

### Similar projects

[Connaisseur](https://sse-secure-systems.github.io/connaisseur/latest/), [Kyverno](https://kyverno.io/)

### Landscape

We will create a PR to add Ratify to the CNCF Landscape in April.

### Business Product or Service to Project separation

Azure Kubernetes Service has developed a managed addon based on the Ratify project for customers. The development and roadmap of the open-source project and the managed addon have always remained entirely separate, and that will continue to be true going forward. 

In addition, Venafi CodeSigning and AWS Signer have related managed services that support Ratify as a verification engine.

### Project presentations

We finished a [presentation](https://github.com/cncf/tag-security/issues/1239) in TAG Security on Apr 24. Here is the Ratify slide deck that we used for [CNCF TAG Security Presentation - Ratify.pdf](https://github.com/cncf/tag-security/files/15087573/CNCF.TAG.Security.Presentation.-.Ratify.pdf)

### Project champions

@lachie83

**Comment by FeynmanZhou** [comment]
Here are the slides that we presented in the CNCF TAG Security review meeting on Apr 24:
[CNCF TAG Security Presentation - Ratify.pdf](https://github.com/cncf/tag-security/files/15087573/CNCF.TAG.Security.Presentation.-.Ratify.pdf)

**Comment by dims** [comment]
Looks like there's a new github org https://github.com/ratify-project/ratify (spun out from deislabs!)

**Comment by dims** [comment]
- Is gatekeeper a mandatory dependency or an optional one? I ask because of the comparison drawn with Connaisseur and Kyverno.
- Do all 3 of the folks that seem to do the majority of the commits work for MSFT? (wasn't sure about BinBin Li), Are there upcoming members of the community who could do more? (poking at mentoring aspects!)

**Comment by FeynmanZhou** [comment]
> Looks like there's a new github org https://github.com/ratify-project/ratify (spun out from deislabs!)

@dims  Yes. Ratify has been transferred from Microsoft-owned GitHub organization to a neutral org recently. The GitHub repo can be automatically redirected to the new URL.

**Comment by FeynmanZhou** [comment]
> * Is gatekeeper a mandatory dependency or an optional one? I ask because of the comparison drawn with Connaisseur and Kyverno.

Currently, Gatekeeper is a core dependency in Kubernetes admission control scenario only. Ratify does not rely on Gatekeeper in other scenarios, such as CLI mode for CI/CD and verification at container runtime (containerd, docker). 


> * Do all 3 of the folks that seem to do the majority of the commits work for MSFT? (wasn't sure about BinBin Li), Are there upcoming members of the community who could do more? (poking at mentoring aspects!)

The majority of commits and contributors are from MSFT so far. AWS, Venafi, and Alibaba adopt Ratify as a part of their solutions so we would expect more members and contributors come from these organizations in the future. This is the motivation and reason for Ratify's donation to CNCF in order to build a vendor-neutral community.

**Comment by mnm678** [comment]
# TAG Security recommendation to TOC

## Project Overview

### Ecosystem Adoption

Ratify has seen engagement with open source projects including ORAS, Notary, and Sigstore. In addition, there has been adoption by vendors such as AWS Signer, Azure Kubernetes Service Image Integrity, and Venafi CodeSign Protect.

### Past TOC Reviews

N/A (Sandbox)

## Security Reviews

### TAG Security Assessments

N/A: We recommend performing a TAG Security Self Assessment.

### Security Audit

N/A

## Best Practices

### Metrics

Ratify achieves 8.4 in OpenSSF Scorecards, which is a great score for a project at this maturity level.

### Static Analysis

Ratify has implemented conformance testing.

## Sub-project Considerations

N/A

## TAG Recommendation to the TOC

Ratify provides a verification framework that integrates with a number of open source projects, with opportunities to integrate with more projects in the supply chain space to provide a single tool for verification. TAG Security would recommend that the TOC move forward with accepting the project into sandbox, with a few recommendations for the project to consider as they mature and move through future CNCF levels:

* Performing a TAG Security self assessment as the project moves toward incubation.  
* Moving vulnerability reporting to a maintainers mailing list or using the Github reporting capabilities rather than going through the Microsoft Security Response Center  
* Adding the OpenSSF Best Practices badge as another metric to track maturity of security posture (https://www.bestpractices.dev/en).

**Comment by FeynmanZhou** [comment]
> # TAG Security recommendation to TOC
> 
> 
> 
> ## Project Overview
> 
> 
> 
> ### Ecosystem Adoption
> 
> 
> 
> Ratify has seen engagement with open source projects including ORAS, Notary, and Sigstore. In addition, there has been adoption by vendors such as AWS Signer, Azure Kubernetes Service Image Integrity, and Venafi CodeSign Protect.
> 
> 
> 
> ### Past TOC Reviews
> 
> 
> 
> N/A (Sandbox)
> 
> 
> 
> ## Security Reviews
> 
> 
> 
> ### TAG Security Assessments
> 
> 
> 
> N/A: We recommend performing a TAG Security Self Assessment.
> 
> 
> 
> ### Security Audit
> 
> 
> 
> N/A
> 
> 
> 
> ## Best Practices
> 
> 
> 
> ### Metrics
> 
> 
> 
> Ratify achieves 8.4 in OpenSSF Scorecards, which is a great score for a project at this maturity level.
> 
> 
> 
> ### Static Analysis
> 
> 
> 
> Ratify has implemented conformance testing.
> 
> 
> 
> ## Sub-project Considerations
> 
> 
> 
> N/A
> 
> 
> 
> ## TAG Recommendation to the TOC
> 
> 
> 
> Ratify provides a verification framework that integrates with a number of open source projects, with opportunities to integrate with more projects in the supply chain space to provide a single tool for verification. TAG Security would recommend that the TOC move forward with accepting the project into sandbox, with a few recommendations for the project to consider as they mature and move through future CNCF levels:
> 
> 
> 
> * Performing a TAG Security self assessment as the project moves toward incubation.  
> 
> * Moving vulnerability reporting to a maintainers mailing list or using the Github reporting capabilities rather than going through the Microsoft Security Response Center  
> 
> * Adding the OpenSSF Best Practices badge as another metric to track maturity of security posture (https://www.bestpractices.dev/en).
> 
> 
> 
> 

Thanks for the support and recommendations from TAG security!Ratify now uses GitHub security advisory reporting process and working on the OSSF Best Practices badge.

In addition, we made some progress for Ratify supply chain security enhancements after the TAG Security review meeting.  @akashsinghal will be able to share some details.

**Comment by akashsinghal** [comment]
Since Ratify's presentation to the TAG Security in May, the Ratify community has been working on addressing TAG Security's feedback on vulnerability management, versioning, and supply chain metadata for release/dev assets:

* Ratify has now adopted Github's vulnerability reporting feature. Guidance is defined [here](https://github.com/ratify-project/ratify/blob/dev/SECURITY.md#reporting-a-vulnerability)
* Ratify now has a clearly defined release versioning guidance [here](https://github.com/ratify-project/ratify/blob/dev/RELEASES.md#git-release-flow). This includes guidance on vulnerability patching on supported versions (read [here](https://github.com/ratify-project/ratify/blob/dev/RELEASES.md#supported-releases)). The project has since released 2 patch versions for the last supported minor release version to address severity alerts that were raised by periodic scanners the project has added + Dependabot. 
* Ratify community has formulated a plan to generate supply chain metadata for all assets including development and release. This effort includes SBOM, SLSA Provenance, and signatures for all release binaries, container images, and development helm charts. Read about the proposal [here](https://github.com/ratify-project/ratify/blob/dev/docs/proposals/Release-Supply-Chain-Metadata.md). Ratify has already added SBOM + Provenance attestations to all images published moving forward, as well as added SBOM generation for release binaries. All development container images/charts are now being signed using cosign + notation.

We appreciate the TAG Security's recommendations!

**Comment by jberkus** [comment]
TAG Contributor strategy has reviewed this project and found the following:

* The [contributor guide](https://github.com/ratify-project/ratify/blob/dev/CONTRIBUTING.md) is above average, containing notes on development environments and testing.  They also have a [reviewing guide](https://github.com/ratify-project/ratify/blob/dev/REVIEWING.md), and a [release process](https://github.com/ratify-project/ratify/blob/dev/RELEASES.md).
* Ratify has no written governance, yet.
* The [roadmap](https://github.com/ratify-project/ratify/blob/dev/ROADMAP.md) is a milestone-organized list of feature goals, and appears to have been created for the 1.2 release.
* There are six [maintainers](https://github.com/ratify-project/ratify/blob/dev/MAINTAINERS),  all of whom work for Microsoft.
* Ratify also has a [deprecation policy](https://github.com/ratify-project/ratify/blob/dev/BREAKING_CHANGE_AND_DEPRECATION.md), marking the first time I've seen one in a Sandbox applicant.

This review is for the TOC’s information only.  Sandbox projects are not required to have full governance or contributor documentation.

**Comment by yizha1** [comment]
Hi @jberkus, thanks for your review comments.

Regarding the following comment:
```
Ratify has no written governance, yet.
```

This repo https://github.com/ratify-project/.github under ratify project listed more documents including https://github.com/ratify-project/.github/blob/main/GOVERNANCE.md. Would you mind checking whether it meets your expectations? Thanks.

**Comment by jberkus** [comment]
Update per above:

* Ratify has a [Maintainer Council type governance](https://github.com/ratify-project/.github/blob/main/GOVERNANCE.md) comprised of Org Owners and Subproject Owners.  While not completely documented, it's a good start for a sandbox project.

Might I suggest adding links to those documents to your [main README](https://github.com/ratify-project/ratify/blob/dev/README.md)?  Like me, new contributors aren't going to look in .github for a governance doc.

**Comment by yizha1** [comment]
Thanks @jberkus. I've submitted a PR https://github.com/ratify-project/ratify/pull/1713 to implement the changes you suggested.

**Comment by FeynmanZhou** [comment]
The vote is passed and closed. May I know what the next step is? Should we start to transfer project trademarks and website hosting (Netlify) to CNCF?

**Comment by bridgetkromhout** [comment]
> The vote is passed and closed. May I know what the next step is? Should we start to transfer project trademarks and website hosting (Netlify) to CNCF?

The next step is that CNCF staff will open a project onboarding issue for Ratify (based on this template: https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/project-onboarding.md) - this may take a few days due to summer vacations. If you would like to start looking at the items on that list now, then you will be ready when the issue is opened. Thanks!

**Comment by Cmierly** [comment]
Welcome and congrats on getting accepted as a CNCF Sandbox project!

You can get started on your on-boarding checklist here: https://github.com/cncf/toc/issues/1412

and if you have any questions, please don't hesitate to reach out!

**Comment by mrbobbytables** [comment]
With https://github.com/cncf/toc/issues/1412 created we can go ahead and close this out :)

Congrats again!
